### ISSUE TITLE
SASLLogin broken on Android

### ISSUE THREAD

**Issue by 2h4u** [MailCore/mailcore2#1563]
I'm writing an App for iOS and Android with mailcore2.

On iOS i'm able to send emails to an specific smtp server, on android i have the exactly same setup:
same server, same port, same credentials,...
authType = SASLLogin
connectionType = StartTLS

But on Android it always fails to send with following error:
com.libmailcore.MailException: Unable to authenticate with the current session's credentials.

The credentials are the same as on iOS...
So it seems that the SASLLogin behaves different on Android as on iOS.

Please fix this

Note: I'm using the precompiled "mailcore2-android-3.aar" from http://d.etpan.org/mailcore2-deps/mailcore2-android/mailcore2-android-3.aar

**Comment by christianlanz** [comment]
It seems you guys are not using the latest version of the cyrus sasl library.

Calling `strings` on sasl binary make it seem that your are using 2.1.25:
```
strings ~/Downloads/cyrus-sasl-android-2/libs/armeabi-v7a/libsasl2.a | grep cyrus
Parameter error in /Users/dvh/MailCore/libetpan/build-android/dependencies/cyrus-sasl/src/cyrus-sasl-2.1.25/build-android/jni/../../lib/auxprop.c near line %d
/Users/dvh/MailCore/libetpan/build-android/dependencies/cyrus-sasl/src/cyrus-sasl-2.1.25/build-android/jni/../../lib
/Users/dvh/MailCore/libetpan/build-android/dependencies/cyrus-sasl/src/cyrus-sasl-2.1.25/build-android/jni/../../include
/Users/dvh/MailCore/libetpan/build-android/dependencies/cyrus-sasl/src/cyrus-sasl-2.1.25/build-android/jni/../../lib/auxprop.c
/Users/dvh/MailCore/libetpan/build-android/dependencies/cyrus-sasl/src/cyrus-sasl-2.1.25/build-android/jni
/Users/dvh/MailCore/libetpan/build-android/dependencies/cyrus-sasl/src/cyrus-sasl-2.1.25/build-android/jni/../../lib
/Users/dvh/MailCore/libetpan/build-android/dependencies/cyrus-sasl/src/cyrus-sasl-2.1.25/build-android/jni/../../include
/Users/dvh/MailCore/libetpan/build-android/dependencies/cyrus-sasl/src/cyrus-sasl-2.1.25/build-android/jni/../../lib/canonusr.c
/Users/dvh/MailCore/libetpan/build-android/dependencies/cyrus-sasl/src/cyrus-sasl-2.1.25/build-android/jni
[...]
```

Relating to the [Cyrus SASL 2.1.26 changelog](http://upstream.rosalinux.ru/changelogs/cyrus-sasl/2.1.26/changelog.html) it seems they fixed the LOGIN issue:
```
* Fixed PLAIN/LOGIN authentication failure when using saslauthd 
  with no auxprop plugins (bug # 3590). 
```

What is the reason for you to use 2.1.25 instead of 2.1.26 which apparently fixed this issue?

I'm going to build the .aar with the latest cyrus sasl binary and get back as soon as I know if this fixes the issue.

**Comment by christianlanz** [comment]
Using the new SASL library does not seem to fix the issue. I still get:
```
com.libmailcore.MailException: Unable to authenticate with the current session's credentials.
```

Maybe it's an issue in libEtPan or mailcore2?

**Comment by dinhviethoa** [comment]
That's an issue with libetpan. I need to move libetpan to use cyrus 2.1.26.
Thanks!

**Comment by christianlanz** [comment]
Can you please comment here as soon as you move libetpan so cyrus 2.1.26? So that I can test it out.
Thanks!

**Comment by dinhviethoa** [comment]
Fixed mailcore2-android-4.aar is available.

**Comment by 2h4u** [comment]
the mailcore2-android-4.aar doesnt fix the problem, still the same error:
com.libmailcore.MailException: Unable to authenticate with the current session's credentials.

**Comment by dinhviethoa** [comment]
I replaced the archive. Could you download it again?

**Comment by 2h4u** [comment]
now the app crashes because the libc++_shared.so file is missing in the .aar

**Comment by dinhviethoa** [comment]
will be fixed. Thanks for reporting back!

**Comment by dinhviethoa** [comment]
I replace the archive again :)
Let me know how it works for you.

**Comment by 2h4u** [comment]
now it doesnt crash anymore but I still get the same error:
com.libmailcore.MailException: Unable to authenticate with the current session's credentials.

tested with the same credentials on iOS and on Android with JavaMail lib, works in both cases fine, so the credentials cant be wrong.
thats really strange
