### ISSUE TITLE
[Bug] - Failed downloading 'https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip'

### ISSUE THREAD

**Issue by pedrosakey** [MailCore/mailcore2#1944]
**Summary**
Installation fail.

**Platform(s)**
```
iOS
```

**Actual outcome**
``
failed downloading 'https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip' which is required by binary target 'MailCore2': downloadError("Error Domain=NSURLErrorDomain Code=-1003 \"A server with the specified hostname could not be found.\" UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x7f7abdf3d940 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 \"(null)\" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0, ipv4, dns, _kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <E9DA454B-3C4C-4B79-BAC9-164EFC59FAB9>.<37>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalDownloadTask <E9DA454B-3C4C-4B79-BAC9-164EFC59FAB9>.<37>\"\n), NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip, NSErrorFailingURLKey=https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip, _kCFStreamErrorDomainKey=12}")
``

**Comment by msheleshey** [comment]
Same issue on my side.

**Comment by IMCHO** [comment]
Also same issue while installing by SPM.

**Comment by bsrz** [comment]
@mateuszjablonski why not just create a GitHub release and attach the zip file there? Why host the framework where the server can be burned?

**Comment by pedrosakey** [comment]
@mateuszjablonski thanks for the answer I tried to build the framework with that script but the output is empty in:
/MailCore-Builds/dependencies/builds/mailcore2-framework-ios
I keep on investigating thank you guys.

**Comment by alessiocasti** [comment]
Getting same issue:

`failed downloading 'https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip' which is required by binary target 'MailCore2': downloadError("Error Domain=NSURLErrorDomain Code=-1003 \"A server with the specified hostname could not be found.\" UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x7fa28198ee00 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 \"(null)\" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0, ipv4, dns, _kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <B4BB840B-8F73-4C6D-9C39-774113C07CEE>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalDownloadTask <B4BB840B-8F73-4C6D-9C39-774113C07CEE>.<1>\"\n), NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip, NSErrorFailingURLKey=https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip, _kCFStreamErrorDomainKey=12}")`

**Comment by alessiocasti** [comment]
> Looks like the server is burned. As a temporary fix, you can build the framework yourselves, there is a `./scripts/build-mailcore2-xcframework-spm.sh` script that you can run to produce XCFramework, and then create a local `Package.swift` file referencing this framework.

I can't build it without errors

**Comment by alessiocasti** [comment]
> 



> @mateuszjablonski thanks for the answer I tried to build the framework with that script but the output is empty in: /MailCore-Builds/dependencies/builds/mailcore2-framework-ios I keep on investigating thank you guys.

@pedrosakey news about building frameworks?

**Comment by pedrosakey** [comment]
@alessiocasti I couldn't build it ¯\_(ツ)_/¯. I found a workaround to make it work. There is a repo with the framework:
https://github.com/pedrosakey/MailCore.xcframework

And then just add it to the project:
https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/

No so clean but it works. Hope it helps.

**Comment by pedrosakey** [comment]
@alessiocasti I would like to share with you that my partner in the project test it with macbook air M1 and it works well. If you check the framework there are both architectures inside or maybe I didn't understand your problem well. Could you describe better so may I can help?

**Comment by alessiocasti** [comment]
> @alessiocasti I would like to share with you that my partner in the project test it with macbook air M1 and it works well. If you check the framework there are both architectures inside or maybe I didn't understand your problem well. Could you describe better so may I can help?

@pedrosakey here (https://github.com/Cleverlance/MailCore.xcframework/tree/master/MailCore.xcframework) there is no armv7 architecture. The xcframework is build only for the archs (folders) listed inside

**Comment by ikemuc** [comment]
> See this: https://github.com/vincedev/MailCoreSPM
> 
> Although only for macOS

Thank you very much! That's my solution!

**Comment by guidedways** [comment]
@mateuszjablonski thanks for this, I've opened a PR for you to review. I've taken the macOS xcframework from and merged it into yours.

So you now have a single xcframework with iOS, iOS Simulator and macOS (arm + x86_64): https://github.com/BeehiveInnovations/MailCore.xcframework

**Comment by guidedways** [comment]
It's also unfortunately missing an iOS Simulator framework for `arm64` - unless someone can get the build scripts functioning again

**Comment by rbosch** [comment]
Same issue with Intel on MacOS (XCode 13.4.1 for Mac App). Any update?

**Comment by dinhvh** [comment]
Can you try to clean build on the latest master?
The build should be fixed now.

**Comment by rbosch** [comment]
@dinhvh i'm still getting this problem: downloads.maddux.cloud, domain doesn't exists anymore.
